// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR3gtYAv8itcgx2wJZjFyiIYMUMhkJFQU',
    appId: '1:568175741091:web:d8cb3c81403cc02141d716',
    messagingSenderId: '568175741091',
    projectId: 'spotify1020',
    authDomain: 'spotify1020.firebaseapp.com',
    storageBucket: 'spotify1020.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDht3nfnvDuOMpONE8th-S0AAjbLnNAbas',
    appId: '1:568175741091:android:dac769b69668e03441d716',
    messagingSenderId: '568175741091',
    projectId: 'spotify1020',
    storageBucket: 'spotify1020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkH-7LgSKtwm4qZQNc7nyaeVcZu1Vu5EE',
    appId: '1:568175741091:ios:fd4bcc433cf3065641d716',
    messagingSenderId: '568175741091',
    projectId: 'spotify1020',
    storageBucket: 'spotify1020.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkH-7LgSKtwm4qZQNc7nyaeVcZu1Vu5EE',
    appId: '1:568175741091:ios:fd4bcc433cf3065641d716',
    messagingSenderId: '568175741091',
    projectId: 'spotify1020',
    storageBucket: 'spotify1020.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR3gtYAv8itcgx2wJZjFyiIYMUMhkJFQU',
    appId: '1:568175741091:web:728c9acf7a382b1341d716',
    messagingSenderId: '568175741091',
    projectId: 'spotify1020',
    authDomain: 'spotify1020.firebaseapp.com',
    storageBucket: 'spotify1020.appspot.com',
  );
}
